Ansible Primer
==============
:Author: Ron Sawyer
:Email: rsawyer@redhat.com
:Date: 28 Jan 2020
:toc:

== Introduction

This is a simple ansible primer to excellerate a quick spin up on how to use ansible, playbooks, roles, etc.

== Other resources

* https://docs.ansible.com/ansible/latest/user_guide/quickstart.html[ansible quick start]
* https://www.tutorialspoint.com/ansible/ansible_quick_guide.html[tutorial quick start]
* https://ryaneschinger.com/blog/ansible-quick-start/[blog quick start]

== Important RPMs

.Essential ansible RPM
* ansible.noarch

== Ansible Basics

==== YAML Playbook example

Directory structure
```
sat
├── ansible.cfg
├── create_sat_server_vm.sh
├── files
│   ├── check_dhcp.sh
│   ├── check_sat.sh
│   ├── sat_firewall.sh
│   └── sat_install.sh
├── hosts
├── manifests
│   ├── manifest_Finance_20200127T154706Z.zip
│   ├── manifest_Operations_20200127T154820Z.zip
│   └── manifest_RONSAT_20200109T181947Z.zip
├── sat_os_config.yml
└── templates
    ├── NetworkManager.j2
    └── resolv.j2
```

Real life playbook example, to configure satellite OS

```
---
- name: "Configure Satellite OS - pre Satellite install"
  hosts: 192.168.122.11
  vars:
    ipa_server_ip: 192.168.122.10

  tasks:

  - name: 'enable required repositories'
    rhsm_repository:
      name:
        - 'rhel-server-rhscl-7-rpms'
        - 'rhel-7-server-satellite-6.6-rpms'
        - 'rhel-7-server-satellite-maintenance-6-rpms'
        - 'rhel-7-server-ansible-2.6-rpms'
        - 'rhel-7-server-extras-rpms'
      state: 'enabled'

  - name: Add required pkgs
    yum:
      name:
        - chrony
        - sos
        - satellite
        - rhel-system-roles
        - ansible
        - NetworkManager-glib
      state: latest

  - name: enable chronyd
    service:
      name: chronyd
      state: started
      enabled: yes

  - name: copy install script that will install Satellite
    copy:
      src: sat_install.sh
      dest: /root/sat_install.sh
      owner: root
      group: root
      mode: 0640

  - name: copy firewall configuration script script as a backup
    copy:
      src: sat_firewall.sh
      dest: /root/sat_firewall.sh
      owner: root
      group: root
      mode: 0640

  - name: copy dhcp test script for testing if DHCP is actually working
    copy:
      src: check_dhcp.sh
      dest: /root/check_dhcp.sh
      owner: root
      group: root
      mode: 0640

  - name: copy sat test script for basic health checks
    copy:
      src: check_sat.sh
      dest: /root/check_sat.sh
      owner: root
      group: root
      mode: 0640

  - name: Configure firewalld ports
    firewalld:
      permanent: yes
      state: enabled
      port: "{{ item }}"
    with_items:
      - 53/udp
      - 53/tcp
      - 67/udp
      - 69/udp
      - 80/tcp
      - 443/tcp
      - 5000/tcp
      - 5647/tcp
      - 8000/tcp
      - 8140/tcp
      - 9090/tcp
    notify: firewalld reload

  - name: firewalld reload
    command: firewall-cmd --reload

  - name: Set up resolv.conf
    template:
      src: resolv.j2
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644

  - name: Config NetworkManager.conf
    template:
      src: NetworkManager.j2
      dest: /etc/NetworkManager/NetworkManager.conf
      owner: root
      group: root
      mode: 0644
```

Template: resolv.j2
```
# ansible modified
search ron.example.com
nameserver {{ ipa_server_ip }}
nameserver 192.168.122.1
```

hosts - inventory file referenced in playbook
```
[idm]
192.168.122.10
[sat]
192.168.122.11
[clients]
192.168.122.201
192.168.122.202
```

== YAML basics

==== syntax

* spacing/indentation matters
* first line starts with three dashes: '---'
* last line ends with three dots: '...' Note, these are optional and usually left out

A list starts each array item with a single dash '-'


==== list example

```
---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango
...
```
Dictionaries is represented in a simple key: value form (the colon must be followed by a space)

==== dictionary example

```
# An employee record
martin:
    name: Martin D'vloper
    job: Developer
    skill: Elite
```
==== a list of dictionaries

```
# Employee records
-  martin:
    name: Martin D'vloper
    job: Developer
    skills:
      - python
      - perl
      - pascal
-  tabitha:
    name: Tabitha Bitumen
    job: Developer
    skills:
      - lisp
      - fortran
      - erlang
```

Lists and dictionaries can be represented in abbreviated form but is discouraged

```
---
martin: {name: Martin D'vloper, job: Developer, skill: Elite}
['Apple', 'Orange', 'Strawberry', 'Mango']
```

booleans

```
create_key: yes
needs_agent: no
knows_oop: True
likes_emacs: TRUE
uses_cvs: false
```

Values can span multiple lines using | or >. Spanning multiple lines using a “Literal Block Scalar” | will include the newlines and any trailing spaces. Using a “Folded Block Scalar” > will fold newlines to spaces; it’s used to make what would otherwise be a very long line easier to read and edit. In either case the indentation will be ignored. Examples are:

```
include_newlines: |
            exactly as you see
            will appear these three
            lines of poetry

fold_newlines: >
            this is really a
            single line of text
            despite appearances
```

While in the above > example all newlines are folded into spaces, there are two ways to enforce a newline to be kept:

```
fold_some_newlines: >
    a
    b

    c
    d
      e
    f
same_as: "a b\nc d\n  e\nf\n"
```

Let’s combine what we learned so far in an arbitrary YAML example. This really has nothing to do with Ansible, but will give you a feel for the format:

```
---
# An employee record
name: Martin D'vloper
job: Developer
skill: Elite
employed: True
foods:
    - Apple
    - Orange
    - Strawberry
    - Mango
languages:
    perl: Elite
    python: Elite
    pascal: Lame
education: |
    4 GCSEs
    3 A-Levels
    BSc in the Internet of Things
```

That’s all you really need to know about YAML to start writing Ansible playbooks.

== lingo

* Control node

Any machine with Ansible installed. You can run commands and playbooks, invoking /usr/bin/ansible or /usr/bin/ansible-playbook, from any control node. You can use any computer that has Python installed on it as a control node - laptops, shared desktops, and servers can all run Ansible. However, you cannot use a Windows machine as a control node. You can have multiple control nodes.

* Managed nodes

The network devices (and/or servers) you manage with Ansible. Managed nodes are also sometimes called “hosts”. Ansible is not installed on managed nodes.

* Inventory

A list of managed nodes. An inventory file is also sometimes called a “hostfile”. Your inventory can specify information like IP address for each managed node. An inventory can also organize managed nodes, creating and nesting groups for easier scaling. To learn more about inventory, see the Working with Inventory section.

* Modules

The units of code Ansible executes. Each module has a particular use, from administering users on a specific type of database to managing VLAN interfaces on a specific type of network device. You can invoke a single module with a task, or invoke several different modules in a playbook. For an idea of how many modules Ansible includes, take a look at the list of all modules.

* Tasks

The units of action in Ansible. You can execute a single task once with an ad-hoc command.

* Playbooks

Ordered lists of tasks, saved so you can run those tasks in that order repeatedly. Playbooks can include variables as well as tasks. Playbooks are written in YAML and are easy to read, write, share and understand.

==== adhoc

```
$ ansible all -m ping
```
response

```
aserver.example.org | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "ping": "pong"
}
```

''ping'' is the module being used.

''all'' are the managed nodes being run against, this means all the hosts in the hosts file.

==== modules

 All modules
 Cloud modules
 Clustering modules
 Commands modules
 Crypto modules
 Database modules
 Files modules
 Identity modules
 Inventory modules
 Messaging modules
 Monitoring modules
 Net Tools modules
 Network modules
 Notification modules
 Packaging modules
 Remote Management modules
 Source Control modules
 Storage modules
 System modules
 Utilities modules
 Web Infrastructure modules
 Windows modules

==== command modules

 command – Execute commands on targets
 expect – Executes a command and responds to prompts
 psexec – Runs commands on a remote Windows host based on the PsExec model
 raw – Executes a low-down and dirty command
 script – Runs a local script on a remote node after transferring it
 shell – Execute shell commands on targets
 telnet – Executes a low-down and dirty telnet command

==== Files modules

 acl – Set and retrieve file ACL information
 archive – Creates a compressed archive of one or more files or trees
 assemble – Assemble configuration files from fragments
 blockinfile – Insert/update/remove a text block surrounded by marker lines
 copy – Copy files to remote locations
 fetch – Fetch files from remote nodes
 file – Manage files and file properties
 find – Return a list of files based on specific criteria
 ini_file – Tweak settings in INI files
 iso_extract – Extract files from an ISO image
 lineinfile – Manage lines in text files
 patch – Apply patch files using the GNU patch tool
 read_csv – Read a CSV file
 replace – Replace all instances of a particular string in a file using a back-referenced regular expression
 stat – Retrieve file or file system status
 synchronize – A wrapper around rsync to make common tasks in your playbooks quick and easy
 tempfile – Creates temporary files and directories
 template – Template a file out to a remote server
 unarchive – Unpacks an archive after (optionally) copying it from the local machine
 xattr – Manage user defined extended attributes
 xml – Manage bits and pieces of XML files or strings

==== help

 ansible-doc <module>

```
 > PING    (/usr/lib/python3.7/site-packages/ansible/modules/system/ping.py)

         A trivial test module, this module always returns `pong' on successful contact. It
         does not make sense in playbooks, but it is useful from `/usr/bin/ansible' to
         verify the ability to login and that a usable Python is configured. This is NOT
         ICMP ping, this is just a trivial test module that requires Python on the remote-
         node. For Windows targets, use the [win_ping] module instead. For Network targets,
         use the [net_ping] module instead.

   * This module is maintained by The Ansible Core Team
 OPTIONS (= is mandatory):

 - data
         Data to return for the `ping' return value.
         If this parameter is set to `crash', the module will cause an exception.
         [Default: pong]
         type: str



 SEE ALSO:
      * Module net_ping
           The official documentation on the net_ping module.
           https://docs.ansible.com/ansible/2.9/modules/net_ping_module.html
      * Module win_ping
           The official documentation on the win_ping module.
           https://docs.ansible.com/ansible/2.9/modules/win_ping_module.html


AUTHOR: Ansible Core Team, Michael DeHaan
        METADATA:
          status:
          - stableinterface
          supported_by: core


EXAMPLES:

# Test we can logon to 'webservers' and execute python with json lib.
# ansible webservers -m ping

# Example from an Ansible Playbook
- ping:

# Induce an exception to see what happens
- ping:
    data: crash


RETURN VALUES:

ping:
    description: value provided with the data parameter
    returned: success
    type: str
    sample: pong
```

```
> COPY    (/usr/lib/python3.7/site-packages/ansible/modules/files/copy.py)

        The `copy' module copies a file from the local or remote machine to a location on
        the remote machine. Use the [fetch] module to copy files from remote locations to
        the local box. If you need variable interpolation in copied files, use the
        [template] module. Using a variable in the `content' field will result in
        unpredictable output. For Windows targets, use the [win_copy] module instead.

  * This module is maintained by The Ansible Core Team
  * note: This module has a corresponding action plugin.

OPTIONS (= is mandatory):

- attributes
        The attributes the resulting file or directory should have.
        To get supported flags look at the man page for `chattr' on the target system.
        This string should contain the attributes in the same order as the one displayed
        by `lsattr'.
        The `=' operator is assumed as default, otherwise `+' or `-' operators need to be
        included in the string.
        (Aliases: attr)[Default: (null)]
        type: str
        version_added: 2.3

- backup
        Create a backup file including the timestamp information so you can get the
        original file back if you somehow clobbered it incorrectly.
        [Default: False]
        type: bool
        version_added: 0.7

- checksum
        SHA1 checksum of the file being transferred.
        Used to validate that the copy of the file was successful.
        If this is not provided, ansible will use the local calculated checksum of the src
        file.
        [Default: (null)]

 ... < lines deleted >

 EXAMPLES:

- name: Copy file with owner and permissions
  copy:
    src: /srv/myfiles/foo.conf
    dest: /etc/foo.conf
    owner: foo
    group: foo
    mode: '0644'

- name: Copy file with owner and permission, using symbolic representation
  copy:
    src: /srv/myfiles/foo.conf
    dest: /etc/foo.conf
    owner: foo
    group: foo
    mode: u=rw,g=r,o=r

- name: Another symbolic mode example, adding some permissions and removing others
  copy:
    src: /srv/myfiles/foo.conf
    dest: /etc/foo.conf
    owner: foo
    group: foo
    mode: u+rw,g-wx,o-rwx

- name: Copy a new "ntp.conf file into place, backing up the original if it differs from the copied version
  copy:
    src: /mine/ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Copy a new "sudoers" file into place, after passing validation with visudo
  copy:
    src: /mine/sudoers
    dest: /etc/sudoers
    validate: /usr/sbin/visudo -csf %s

- name: Copy a "sudoers" file on the remote machine for editing
  copy:
    src: /etc/sudoers
    dest: /etc/sudoers.edit
    remote_src: yes
    validate: /usr/sbin/visudo -csf %s

- name: Copy using inline content
  copy:
    content: '# This file was moved to /etc/other.conf'
    dest: /etc/mine.conf

- name: If follow=yes, /path/to/file will be overwritten by contents of foo.conf
  copy:
    src: /etc/foo.conf
    dest: /path/to/link  # link to /path/to/file
    follow: yes

- name: If follow=no, /path/to/link will become a file and be overwritten by contents of foo.conf
  copy:
    src: /etc/foo.conf
    dest: /path/to/link  # link to /path/to/file
    follow: no

  ... < lines deleted >

```

ansible.cfg

```
[defaults]
inventory      = hosts
forks          = 5
remote_user    = root
roles_path     = /usr/share/ansible/roles
ask_pass       = True
#log_path       =/var/log/ansible.log
inventory_ignore_extensions = ~, .swp, .md, .adoc, .csv, .retry, .pyc, .pyo, .example
display_skipped_hosts = False
deprecation_warnings = False
command_warnings = False
nocows         = 1
retry_files_enabled = False
host_key_checking = False

[privilege_escalation]
become         = False
#become_method  = sudo
#become_user    = root
#become_ask_pass= True

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=900s
control_path = %(directory)s/%%h-%%r
#pipelining = False

```

== Variables

* There are many places to put variables
. hosts/inventory file
. playbook
. file
. directory

Variable names should be letters, numbers, and underscores. Variables should always start with a letter.

```
foo_port is a great variable. foo5 is fine too.

foo-port, foo port, foo.port and 12 are not valid variable names.
```

==== Using variables in playbooks

```
{{ variable_name }}
```
YAML syntax requires that if you start a value with {{ foo }} you quote the whole line, since it wants to be sure you aren’t trying to start a YAML dictionary.

Note, this won’t work:

- hosts: app_servers
  vars:
      app_path: {{ base_path }}/22

Do it like this and you’ll be fine:

- hosts: app_servers
  vars:
       app_path: "{{ base_path }}/22"


If multiple variables of the same name are defined in different places, they get overwritten in a certain order.

Here is the order of precedence from least to greatest (the last listed variables winning prioritization):

```
       command line values (eg “-u user”)
       role defaults [1]
       inventory file or script group vars [2]
       inventory group_vars/all [3]
       playbook group_vars/all [3]
       inventory group_vars/* [3]
       playbook group_vars/* [3]
       inventory file or script host vars [2]
       inventory host_vars/* [3]
       playbook host_vars/* [3]
       host facts / cached set_facts [4]
       play vars
       play vars_prompt
       play vars_files
       role vars (defined in role/vars/main.yml)
       block vars (only for tasks in block)
       task vars (only for the task)
       include_vars
       set_facts / registered vars
       role (and include_role) params
       include params
       extra vars (always win precedence)
```

==== Variables discovered from systems: Facts

There are other places where variables can come from, but these are a type of variable that are discovered, not set by the user.

Facts are information derived from speaking with your remote systems. You can find a complete set under the ansible_facts variable, most facts are also ‘injected’ as top level variables preserving the ansible_ prefix, but some are dropped due to conflicts. This can be disabled via the INJECT_FACTS_AS_VARS setting.

An example of this might be the IP address of the remote host, or what the operating system is.

To see what information is available, try the following in a play:

```
       - debug: var=ansible_facts
```

To see the ‘raw’ information as gathered:

```
       ansible hostname -m setup
```

This will return a large amount of variable data, which may look like this on Ansible 2.7:

```
       {
           "ansible_all_ipv4_addresses": [
               "REDACTED IP ADDRESS"
           ],
           "ansible_all_ipv6_addresses": [
               "REDACTED IPV6 ADDRESS"
           ],
           "ansible_apparmor": {
               "status": "disabled"
           },
           "ansible_architecture": "x86_64",
           "ansible_bios_date": "11/28/2013",
           "ansible_bios_version": "4.1.5",
           "ansible_cmdline": {
               "BOOT_IMAGE": "/boot/vmlinuz-3.10.0-862.14.4.el7.x86_64",
               "console": "ttyS0,115200",
               "no_timer_check": true,
               "nofb": true,
               "nomodeset": true,
               "ro": true,
               "root": "LABEL=cloudimg-rootfs",
               "vga": "normal"
           },
           "ansible_date_time": {
               "date": "2018-10-25",
               "day": "25",
               "epoch": "1540469324",
               "hour": "12",
               "iso8601": "2018-10-25T12:08:44Z",
               "iso8601_basic": "20181025T120844109754",
               "iso8601_basic_short": "20181025T120844",
               "iso8601_micro": "2018-10-25T12:08:44.109968Z",
               "minute": "08",
               "month": "10",
               "second": "44",
               "time": "12:08:44",
               "tz": "UTC",
               "tz_offset": "+0000",
               "weekday": "Thursday",
               "weekday_number": "4",
               "weeknumber": "43",
               "year": "2018"
           },
           "ansible_default_ipv4": {
               "address": "REDACTED",
               "alias": "eth0",
               "broadcast": "REDACTED",
               "gateway": "REDACTED",
               "interface": "eth0",
               "macaddress": "REDACTED",
               "mtu": 1500,
               "netmask": "255.255.255.0",
               "network": "REDACTED",
               "type": "ether"
           },
           "ansible_default_ipv6": {},
           "ansible_device_links": {
               "ids": {},
               "labels": {
                   "xvda1": [
                       "cloudimg-rootfs"
                   ],
                   "xvdd": [
                       "config-2"
                   ]
               },
               "masters": {},
               "uuids": {
                   "xvda1": [
                       "cac81d61-d0f8-4b47-84aa-b48798239164"
                   ],
                   "xvdd": [
                       "2018-10-25-12-05-57-00"
                   ]
               }
           },
 ...

```
